name: Prod Deploy

on:
  push:
    tags:
      - '**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Build and Publish head Docker image
        uses: VaultVulp/gp-docker-action@1.1.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: block-explorer-frontend
          image-tag: prod
      - name: Init folder on server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{secrets.REMOTE_HOST_PROD}}
          username: ${{secrets.REMOTE_USER_PORD}}
          key: ${{secrets.SSH_KEY}}
          script: mkdir -p ${{secrets.REMOTE_DIR}}

      - name: Deploy image and run
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{secrets.REMOTE_HOST_PROD}}
          username: ${{secrets.REMOTE_USER_PORD}}
          key: ${{secrets.SSH_KEY}}
          script: |
            cd ${{secrets.REMOTE_DIR}}
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://docker.pkg.github.com -u publisher --password-stdin
            docker-compose down
            docker-compose pull
            docker-compose up -d
